/**
 * Bundled audiobook audio — chapters that ship inside the APK/AAB, so these
 * books play offline from the moment the app is installed (no download step).
 *
 * Keep this list SHORT: the app binary grows by the full size of every file
 * here (~0.5 MB per audio-minute at 64 kbps). Long books belong on the CDN via
 * the TTS agent; only compact, high-value titles are bundled.
 *
 * The map is keyed by chapter id ({bookId}_{index}) and returns the Metro
 * asset module for expo-av. Regenerated by tools/tts_agent output — keep in
 * sync with seed/catalog.json bundled:// chapter URLs.
 */

/* eslint-disable @typescript-eslint/no-var-requires */

const BUNDLED_CHAPTERS: Record<string, number> = {
  'forty-hadith-nawawi_0': require('../../assets/audiobooks/forty-hadith-nawawi/000.mp3'),
  'forty-hadith-nawawi_1': require('../../assets/audiobooks/forty-hadith-nawawi/001.mp3'),
  'forty-hadith-nawawi_2': require('../../assets/audiobooks/forty-hadith-nawawi/002.mp3'),
  'forty-hadith-qudsi_0': require('../../assets/audiobooks/forty-hadith-qudsi/000.mp3'),
  'forty-hadith-qudsi_1': require('../../assets/audiobooks/forty-hadith-qudsi/001.mp3'),
  'forty-hadith-qudsi_2': require('../../assets/audiobooks/forty-hadith-qudsi/002.mp3'),
  'forty-hadith-qudsi_3': require('../../assets/audiobooks/forty-hadith-qudsi/003.mp3'),
};

export function getBundledSource(chapterId: string): number | null {
  return BUNDLED_CHAPTERS[chapterId] ?? null;
}

export function isBookBundled(bookId: string): boolean {
  return Object.keys(BUNDLED_CHAPTERS).some((id) => id.startsWith(`${bookId}_`));
}
